### ISSUE TITLE
debops lxd ?

### ISSUE THREAD

**Issue by niccolox** [debops/ansible-lxc#33]
hi

any thoughts on debops lxd ?

there is a stub there
https://github.com/ser/debops-lxd/issues/1

its looking like the Debian LXD port is almost done

https://wiki.debian.org/LXD
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=768073

**Comment by drybjed** [comment]
Unfortunately, it seems that the LXD has not made it to Debian Stretch before the freeze. I know it's available on Ubuntu, however I like to stick to Debian when possible. If someone else works on an LXD role with ubuntu in mind, I can take a look.

I think that LXD support will be available in Stretch later via `stretch-backports`, however it will be most likely in about 6 months or so, after next Stable release. I plan to look at it then. In the meantime, I'll try to update the LXC support in Stretch.

**Comment by niccolox** [comment]
no worries, LXD/LXC is great
