### ISSUE TITLE
Convert to using ansible-modules-extras/cloud/lxc module

### ISSUE THREAD

**Issue by odyssey4me** [debops/ansible-lxc#8]
Recently a module was merged into ansible-modules-extras which provides a state-orientated way of building and managing lxc containers: https://github.com/ansible/ansible-modules-extras/pull/123

It would be great if this role could be converted to use this module instead of using the current command format.

**Comment by drybjed** [comment]
Sounds like a good idea. Will look into it, thanks for the heads up. :-)

**Comment by drybjed** [comment]
The [`debops.lxc` role](https://github.com/debops/debops/tree/master/ansible/roles/debops.lxc) included in the [DebOps monorepo](https://github.com/debops/debops/) now uses the `lxc_container` Ansible module to manage LXC containers on the hosts. Closing this issue as resolved.
